### ISSUE TITLE
[BUG] wrong return value of activeBillingAddress

### ISSUE THREAD

**Issue by niklaswolf** [shopware/frontends#376] opened 2023-08-24 09:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`const {activeBillingAddress} = useSessionContext()` returns the default billing address.
See https://github.com/shopware/frontends/blob/main/packages/composables/src/useSessionContext.ts#L204 

### Expected Behavior

It returns the active billing address.

### Steps To Reproduce

-

### Anything else?

There was a change here: https://github.com/shopware/frontends/commit/b9881b89da2605a5ccd78617d3f8ae8e05e8c43a#diff-7b6fd21283d6beab44dc4e8fd6fb7ba2598459b54b0d1cd9daca15b9f93f7e5b 
```[tasklist]
### Tasks
```

**Comment by mkucmus** [comment] 2023-08-25 07:42
thanks @niklaswolf for reporting the issue. sadly, the API has changed and the source of active billing address. Currently the issue is being fixed in the core to have something similar to active shipping address (`shippingLocation`) or to bring back the previous logic, because now, `activeBillingAddress` is not set for a customer.

internal issue: `NEXT-28627`

**Comment by niklaswolf** [comment] 2023-08-25 14:30
@mkucmus okay, but there are many many projects that still use Shopware 6.4. 
For those the whole thing is broken without notice now, which should not happen in my opinion!

**Comment by SuddenDev** [comment] 2023-09-20 19:06
Any idea when this will be fixed? Also, is there a recommended workaround?
I think a note in the Documentation is really needed, as I've been trying to debug my application for over an hour now to figure out why THE OFFICIAL Demo does not work setting the billing address.

For now I'll just set it as the default billing address, but this is not ideal.

**Comment by niklaswolf** [comment] 2023-09-21 16:25
Can confirm that this fixes it. Applied the change as a patch today on a Shopware 6.5.5.x instance today.
Now only the composable has to be changed back...

**Closed** 2023-10-02 09:31 UTC
Labels: bug
