### ISSUE TITLE
[BUG] Search/listing page refactoring

### ISSUE THREAD

**Issue by mdanilowicz** [shopware/frontends#1057] opened 2024-06-25 10:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Problems: 
- Filters are changed after refreshing the page. This problem exists because we are building it at the init page request. After applying any filter, the context changes, and we do not refresh the list. To decide what strategy should be implemented

What we need:
- Only one function will handle API calls (currently, we have two different calls. From `search.vue` and `useListing` composable
- We should send two requests. Init a request to give us all available filters for searching and the next one to get active filters.
- Change the structure of the filter request. It should be a part of the filter property.

- Add examples of how to use listing/search filters with different variants

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by BrocksiNet** [comment] 2024-10-02 08:23
This issue is a duplicate of #841.
So I close this and add your description as a comment to 841.

**Closed by BrocksiNet** 2024-10-02 08:23 UTC
Labels: bug
