### ISSUE TITLE
[BUG] Missing CMS component

### ISSUE THREAD

**Issue by mdanilowicz** [shopware/frontends#1373] opened 2024-10-21 13:34 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Missing CMS components for https://frontends-demo.vercel.app/CMS/CMS-test/

```
CmsBlockImageGalleryBig
CmsBlockSpatialViewer
```

### Environment

- OS:
- Node:
- pnpm:

**Comment by BrocksiNet** [comment] 2024-10-21 17:33
This issue is a duplicate of 🔽 

CmsBlockSpatialViewer ➡ https://github.com/shopware/frontends/issues/1305
CmsBlockImageGalleryBig ➡ https://github.com/shopware/frontends/issues/1306

**Closed by BrocksiNet** 2024-10-21 17:33 UTC
Labels: bug
